version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install .[docs]
      - pip install sphinx furo pygments sphinx_copybutton sphinx-autobuild httpx xmltodict
      - cd docs/compiler && python compiler.py

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub